In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10, 1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr = np.ones((3, 3)) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
arr = np.ones((3, 3), dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
arr = np.full((3, 3), fill_value=True, dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
arr = np.arange(0, 10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


In [7]:
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
arr_2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [11]:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [13]:
arr = np.array([1,2,3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [14]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 6  9 10]


In [15]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [16]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(np.where(a<b, b, a))

[6 7 9 8 9 7 5]


In [17]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('./dog.jpeg')

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 61.9MB/s]


In [19]:
gray_img_01 = (np.max(img, axis=-1) + np.min(img, axis=-1)) / 2
gray_img_01[0, 0]

102.5

In [21]:
gray_img_02 = np.sum(img, axis=2) / 3
gray_img_02[0, 0]

107.66666666666667

In [22]:
gray_img_03 = img[:, :, 0] * .21 + img[:, :, 1] * .72 + img[:, :, 2] * .07
gray_img_03[0, 0]

126.22999999999999

In [23]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 20.5MB/s]


In [24]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [25]:
print(np.max(data[:, 3]))
print(np.argmax(data[:, 3]))

27.0
175


In [26]:
np.mean(data[:, 0])

147.0425

In [27]:
len(data[data[:, 3] >= 20])

40

In [28]:
np.mean(data[:, 1][data[:, 3] >= 15])

26.22293577981651

In [29]:
np.sum(data[:, 3][data[:, 2] >= np.mean(data[:, 2])])

1405.1

In [31]:
A = np.mean(data[:, 3])
scores = np.where(data[:, 3] > A, 'Good', np.where(data[:, 3] < A, 'Bad', 'Average'))
scores[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')

In [34]:
index = np.argmin(np.abs(data[:, 3] - np.mean(data[:, 3])))
A = data[index, 3]
scores = np.where(data[:, 3] > A, 'Good', np.where(data[:, 3] < A, 'Bad', 'Average'))
scores[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')